from pyspark.sql.types import (
    BooleanType,
    DateType,
    DoubleType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
)

RAW_BOX_SCORE_SCHEMA = StructType(
    [
        StructField("game_id", StringType(), nullable=False),
        StructField("game_date", DateType(), nullable=False),
        StructField("season", IntegerType(), nullable=False),
        StructField("season_type", StringType(), nullable=False),
        StructField("team_id", IntegerType(), nullable=False),
        StructField("team_abbreviation", StringType(), nullable=False),
        StructField("team_city", StringType(), nullable=True),
        StructField("matchup", StringType(), nullable=True),
        StructField("wl", StringType(), nullable=True),
        StructField("player_id", IntegerType(), nullable=True),
        StructField("player_name", StringType(), nullable=True),
        StructField("start_position", StringType(), nullable=True),
        StructField("min", StringType(), nullable=True),
        StructField("pts", IntegerType(), nullable=True),
        StructField("reb", IntegerType(), nullable=True),
        StructField("ast", IntegerType(), nullable=True),
        StructField("stl", IntegerType(), nullable=True),
        StructField("blk", IntegerType(), nullable=True),
        StructField("tov", IntegerType(), nullable=True),
        StructField("pf", IntegerType(), nullable=True),
        StructField("fgm", IntegerType(), nullable=True),
        StructField("fga", IntegerType(), nullable=True),
        StructField("fg3m", IntegerType(), nullable=True),
        StructField("fg3a", IntegerType(), nullable=True),
        StructField("ftm", IntegerType(), nullable=True),
        StructField("fta", IntegerType(), nullable=True),
        StructField("plus_minus", IntegerType(), nullable=True),
    ]
)

PROCESSED_SCHEMA = StructType(
    [
        StructField("season", IntegerType(), nullable=False),
        StructField("game_date", DateType(), nullable=False),
        StructField("game_id", StringType(), nullable=False),
        StructField("season_type", StringType(), nullable=False),
        StructField("team_id", IntegerType(), nullable=False),
        StructField("team_abbreviation", StringType(), nullable=False),
        StructField("opponent_abbreviation", StringType(), nullable=True),
        StructField("is_home", BooleanType(), nullable=True),
        StructField("win", BooleanType(), nullable=True),
        StructField("pts", LongType(), nullable=True),
        StructField("reb", LongType(), nullable=True),
        StructField("ast", LongType(), nullable=True),
        StructField("tov", LongType(), nullable=True),
        StructField("fg_pct", DoubleType(), nullable=True),
        StructField("fg3_pct", DoubleType(), nullable=True),
        StructField("ft_pct", DoubleType(), nullable=True),
        StructField("effective_fg_pct", DoubleType(), nullable=True),
        StructField("true_shooting_pct", DoubleType(), nullable=True),
        StructField("assist_to_turnover", DoubleType(), nullable=True),
        StructField("top_scorer", StringType(), nullable=True),
        StructField("top_rebounder", StringType(), nullable=True),
        StructField("top_playmaker", StringType(), nullable=True),
    ]
)
